SwitchSelect/Models/Cliente/Cliente.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace SwitchSelect.Models;

[Table("Clientes")]
public class Cliente
{
    [Key]
    public int Id { get; set; }
    [Required(ErrorMessage = "Informe o nome")]
    [StringLength(100, ErrorMessage = "Número máximo de caracter 100")]
    public string Nome { get; set; }

    [Required]
    public DateTime DataDeNascimento { get; set; }

    [Required]
    [StringLength(10)]
    public string Genero { get; set; }

    [Required]
    [StringLength(100)]
    public string Email { get; set; }

    [Required(ErrorMessage = "Informe o Cpf")]
    [StringLength(11, MinimumLength = 11, ErrorMessage = "Cpf inválido")]
    [Display(Name ="CPF")]
    public string Cpf { get; set; }
    [Required(ErrorMessage = "Informe o RG")]
    [StringLength(9, ErrorMessage = "Número máximo de caracter 9")]
    public string RG { get; set; }
    public List <Telefone> Telefones { get; set; } = new List <Telefone> ();
    public List<Endereco> Enderecos { get; set; } = new List<Endereco>();
    public List<Cartao> Cartoes { get; set; } = new List<Cartao>();

}

SwitchSelect/Models/ViewModels/ClienteViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SwitchSelect.Models.ViewModels;

public class ClienteViewModel
{
    // Informações do Cliente
    public int Id { get; set; }

    [Required(ErrorMessage = "Informe o nome")]
    [StringLength(100, ErrorMessage = "Número máximo de caracter 100")]
    public string Nome { get; set; }

    [Required]
    public DateTime DataDeNascimento { get; set; }

    [Required]
    [StringLength(10)]
    public string Genero { get; set; }


    [Required]
    [StringLength(100)]
    public string Email { get; set; }

    [Required(ErrorMessage = "Informe o Cpf")]
    [StringLength(11, MinimumLength = 11, ErrorMessage = "Cpf inválido")]
    [Display(Name = "CPF")]
    public string Cpf { get; set; }

    [Required(ErrorMessage = "Informe o RG")]
    [StringLength(9, ErrorMessage = "Número máximo de caracter 9")]
    public string RG { get; set; }

    //informação de telefone
    public TipoTelefone TipoTelefone { get; set; }
    [Required(ErrorMessage = "Informe DDD")]
    [StringLength(3)]
    public string DDD { get; set; }

    [Required(ErrorMessage = "Informe Telefone")]
    [StringLength(9)]
    [Display(Name = "Telefone")]
    public string NumeroTelefone { get; set; }
}

SwitchSelect/Controllers/CartaoController.cs
using Microsoft.AspNetCore.Mvc;
using SwitchSelect.Models;
using SwitchSelect.Models.ViewModels;
using SwitchSelect.Repositorios.Interfaces;
using SwitchSelect.Service;

namespace SwitchSelect.Controllers
{
    public class CartaoController : Controller
    {
        private readonly ICartaoRepositorio _cartaoRepositorio;
        private readonly CartaoService _cartaoService;

        public CartaoController(CartaoService service, ICartaoRepositorio cartaoRepositorio)
        {
            _cartaoService = service;
            _cartaoRepositorio = cartaoRepositorio;
        }

        public IActionResult Create(int clienteId)
        {
            var viewModel = new CartaoViewModel
            {
                ClienteId = clienteId
            };
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CartaoViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            await _cartaoService.CriarCartaoAsync(model);
            return RedirectToAction(nameof(CartaoList), new { clienteId = model.ClienteId });
        }
        public IActionResult CartaoList(int clienteId)
        {
            var cartoes = _cartaoRepositorio.ObterCartaoPorCliente(clienteId);

            //convertendo model para viewmodel
            var cartoesViewModel = cartoes.Select(c => new CartaoViewModel
            {
                Id = c.Id,
                ClienteId = c.ClienteId,
                NumeroCartao = c.NumeroCartao,
                TitularDoCartao = c.TitularDoCartao,
                CpfTitularCartao = c.CpfTitularCartao,
                MesValidade = c.MesValidade,
                AnoValidade = c.AnoValidade,
                DataValidade = c.DataValidade,
                CVV = c.CVV,
                TipoCartao = c.TipoCartao,
            }).ToList();
            if(cartoesViewModel is null)
            {
                return NotFound();
            }
            foreach(var cartao in cartoesViewModel)
            {
                var numeroCartao = cartao.NumeroCartao;
                cartao.CartaoQuatroDigito = _cartaoService.FormatarUltimosQuatroDigitos(numeroCartao);
            }
            ViewData["ClienteID"] = clienteId;
            return View(cartoesViewModel);
        }

        public IActionResult Edit(int? id, int clienteId)
        {
            if (id == null)
            {
                return NotFound();
            }
            var cartaoViewModel = _cartaoService.ObterCartaoPorId(id.Value);
            cartaoViewModel.ClienteId = clienteId;
            if(cartaoViewModel is null)
            {
                return NotFound();
            }
            return View(cartaoViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [FromForm] CartaoViewModel cartaoViewModel)
        {
            try
            {
                if (id != cartaoViewModel.Id)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    var sucesso = await _cartaoService.EditCartao(id, cartaoViewModel);
                    if (sucesso)
                    {
                        var clienteId = cartaoViewModel.ClienteId;
                        return RedirectToAction("CartaoList", new { clienteId = clienteId });
                    }
                    else
                    {
                        // Retornar uma view de erro personalizada com uma mensagem específica
                        
                        return View("Error");
                    }
                }
                return View(cartaoViewModel);
            }
            catch (Exception ex)
            {
                // Logue a exceção para registrar detalhes
                Console.WriteLine(ex);
                ViewData["ErrorMessage"] = ex;
                // Passe a mensagem de exceção como modelo para a view de erro
                return RedirectToAction("Error", new { message = ex.Message });
            }
        }

        [HttpGet]
        public IActionResult Delete(int? id, int clienteId)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }


            var cartao = _cartaoRepositorio.Cartoes.FirstOrDefault(c => c.Id == id);

            if(cartao == null)
            {
                return NotFound();
            }
            var numeroCartao = cartao.NumeroCartao;
            var cartaoViewModel = new CartaoViewModel
            {
                Id = cartao.Id,
                ClienteId = clienteId,
                CartaoQuatroDigito = _cartaoService.FormatarUltimosQuatroDigitos(numeroCartao),
            };
            return View(cartaoViewModel);
        }

        [HttpPost,ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmacao(int id, int clienteId)
        {
            await _cartaoService.DeleteCartao(id);
            return RedirectToAction(nameof(CartaoList), new { clienteId = clienteId });
        }

    }
}

SwitchSelect/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using SwitchSelect.Data;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using SwitchSelect.Models.ViewModels;
using SwitchSelect.Service;


namespace SwitchSelect.Controllers
{
    public class ClienteController : Controller
    {
        private readonly SwitchSelectContext _context;
        private readonly ClienteService _clienteService;

        public ClienteController(SwitchSelectContext context, ClienteService service)
        {
            _context = context;
            _clienteService = service;
        }

        public IActionResult ListaCliente()
        {
            var list = _clienteService.ListarClientes();
            return View(list);
        }

        public IActionResult PerfilUsuario()
        {
            return View();
        }

        public IActionResult PesquisarClientePorCpf()
        {
            return View();
        }

        public IActionResult AreaCliente(int id)
        {
            var cliente = _clienteService.ObterClientePorId(id);
            //var usuario = HttpContext.Session.GetString("usuario");
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        public IActionResult DadosPessoais(int id)
        {
            var cliente = _clienteService.ObterClientePorId(id);
            if (cliente == null) return NotFound();
            return View(cliente);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] ClienteCompletoViewModel model)
        {
            if (ModelState.IsValid)
            {
                await _clienteService.CriarClienteAsync(model);
                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }

        public IActionResult Edit(int? id, string origem)
        {
            ViewBag.Origem = origem;
            if (id == null)
            {
                return NotFound();
            }

            var clienteViewModel = _clienteService.ObterClientePorId(id.Value);
            if (clienteViewModel == null)
            {
                return NotFound();
            }

            return View(clienteViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [FromForm] ClienteCompletoViewModel clienteViewModel)
        {

            if (id != clienteViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                var sucesso = await _clienteService.EditarClienteAsync(id, clienteViewModel);
                if (sucesso)
                {
                    return RedirectToAction("AdminListaCliente", "Admin");
                }
                else
                {
                    return NotFound();
                }
            }
            return View(clienteViewModel);
        }

        public IActionResult EditDadosPessoais(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var clienteViewModel = _clienteService.ObterClientePorIdDadosPessoais(id.Value);
            if (clienteViewModel == null)
            {
                return NotFound();
            }

            return View(clienteViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditDadosPessoais(int id, [FromForm] ClienteDadosPessoaisViewModel clienteDadosPessoais)
        {
            if (id != clienteDadosPessoais.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var sucesso = await _clienteService.EditarClienteDadosPessoais(id, clienteDadosPessoais);
                if (sucesso)
                {
                    return RedirectToAction("DadosPessoais", "Cliente", new { id = id });
                }
            }
            return View(clienteDadosPessoais);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(c => c.Id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            var viewModel = new ClienteDeleteViewModel
            {
                Id = cliente.Id,
                Nome = cliente.Nome
            };

            return View(viewModel);
        }


        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _clienteService.DeleteClienteAsync(id);
            return RedirectToAction("Index", "Home");
        }



    }
}

SwitchSelect/Controllers/CupomController.cs
using Microsoft.AspNetCore.Mvc;

namespace SwitchSelect.Controllers
{
    public class CupomController : Controller
    {
        public IActionResult CupomList()
        {
            return View();
        }
    }
}

SwitchSelect/Controllers/PedidoController.cs
using Microsoft.AspNetCore.Mvc;

namespace SwitchSelect.Controllers
{
    public class PedidoController : Controller
    {
        public IActionResult FinalizarPedido()
        {
            return View();
        }
        public IActionResult Pedido()
        {
            return View();
        }
        public IActionResult StatusPedido()
        {
            return View();
        }
        public IActionResult TrocaPedido()
        {
            return View();
        }

        public IActionResult StatusTroca()
        {
            return View();
        }

        public IActionResult DevolucaoPedido()
        {
            return View();
        }

        public IActionResult StatusDevolucao()
        {
            return View();
        }

        public IActionResult PedidoList()
        {
            return View();
        }
    }
}

SwitchSelect/Views/Cliente/AreaCliente.cshtml
@model SwitchSelect.Models.ViewModels.ClienteCompletoViewModel

<h2>Área do cliente</h2>

<div>
    <dl class="row">

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>


    </dl>
    <div class="align-items-start">
        <a asp-controller="Pedido" asp-action="PedidoList" class="btn btn-primary">Pedidos</a>
        <a asp-controller="Cupom" asp-action="CupomList" class="btn btn-primary">Meus cupons</a>
        <a asp-controller="Cartao" asp-action="CartaoList" asp-route-ClienteId="@Model.Id" class="btn btn-primary" id="cartao">Metodo de pagamento</a>
        <a asp-controller="Cliente" asp-action="DadosPessoais" asp-route-id="@Model.Id" class="btn btn-primary">Dados pessoais</a>
        <a asp-controller="Endereco" asp-action="EnderecoList" asp-route-ClienteId="@Model.Id" class="btn btn-primary" id="endereco">Endereço</a>
        
    </div>
    <br />
    <a asp-controller="Home" asp-action="Index" class="btn btn-link">Voltar</a>
</div>

SwitchSelect/Views/Cliente/ClienteEdit.cshtml
@model SwitchSelect.Models.ViewModels.ClienteViewModel

@{
    ViewData["Title"] = "ClienteEdit";
}

<h1>Editar Client</h1>

<h4>ClienteViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ClienteEdit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cpf" class="control-label"></label>
                <input asp-for="Cpf" class="form-control" />
                <span asp-validation-for="Cpf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RG" class="control-label"></label>
                <input asp-for="RG" class="form-control" />
                <span asp-validation-for="RG" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoTelefone" class="control-label"></label>
                <select asp-for="TipoTelefone" class="form-control"></select>
                <span asp-validation-for="TipoTelefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DDD" class="control-label"></label>
                <input asp-for="DDD" class="form-control" />
                <span asp-validation-for="DDD" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroTelefone" class="control-label"></label>
                <input asp-for="NumeroTelefone" class="form-control" />
                <span asp-validation-for="NumeroTelefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoEndereco" class="control-label"></label>
                <select asp-for="TipoEndereco" class="form-control"></select>
                <span asp-validation-for="TipoEndereco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoResidencia" class="control-label"></label>
                <select asp-for="TipoResidencia" class="form-control"></select>
                <span asp-validation-for="TipoResidencia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoLogradouro" class="control-label"></label>
                <select asp-for="TipoLogradouro" class="form-control"></select>
                <span asp-validation-for="TipoLogradouro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Logradouro" class="control-label"></label>
                <input asp-for="Logradouro" class="form-control" />
                <span asp-validation-for="Logradouro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Numero" class="control-label"></label>
                <input asp-for="Numero" class="form-control" />
                <span asp-validation-for="Numero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CEP" class="control-label"></label>
                <input asp-for="CEP" class="form-control" />
                <span asp-validation-for="CEP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Complemento" class="control-label"></label>
                <input asp-for="Complemento" class="form-control" />
                <span asp-validation-for="Complemento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bairro" class="control-label"></label>
                <input asp-for="Bairro" class="form-control" />
                <span asp-validation-for="Bairro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cidade" class="control-label"></label>
                <input asp-for="Cidade" class="form-control" />
                <span asp-validation-for="Cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroCartao" class="control-label"></label>
                <input asp-for="NumeroCartao" class="form-control" />
                <span asp-validation-for="NumeroCartao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TitularDoCartao" class="control-label"></label>
                <input asp-for="TitularDoCartao" class="form-control" />
                <span asp-validation-for="TitularDoCartao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CpfTitularCartao" class="control-label"></label>
                <input asp-for="CpfTitularCartao" class="form-control" />
                <span asp-validation-for="CpfTitularCartao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataValidade" class="control-label"></label>
                <input asp-for="DataValidade" class="form-control" />
                <span asp-validation-for="DataValidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CVV" class="control-label"></label>
                <input asp-for="CVV" class="form-control" />
                <span asp-validation-for="CVV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoCartao" class="control-label"></label>
                <select asp-for="TipoCartao" class="form-control"></select>
                <span asp-validation-for="TipoCartao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SwitchSelect/Views/Cliente/DadosPessoais.cshtml
@model SwitchSelect.Models.ViewModels.ClienteCompletoViewModel

@{
    ViewData["Title"] = "Dados Pessoais";
}

<h4>Dados pessoais</h4>

<div class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Nome):
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Nome)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Genero):
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Genero)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.DataDeNascimento):
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.DataDeNascimento)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Cpf):
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Cpf)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.RG):
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.RG)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Email):
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Email)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.NumeroTelefone):
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.NumeroTelefone)
    </dd>
    
</div>
<a asp-controller="Cliente" asp-action="EditDadosPessoais" asp-route-id="@Model?.Id"  class="btn btn-primary">Editar</a>
<a asp-action="Delete" asp-route-id="@Model.Id" class="col-sm-2 btn btn-danger ">Excluir minha conta</a>
<br />
<a asp-action="AreaCliente" asp-route-id="@Model.Id">Voltar</a>

SwitchSelect/Views/Cliente/Delete.cshtml
@model SwitchSelect.Models.ViewModels.ClienteDeleteViewModel 

<h1>Deletar Cliente</h1>

<p>Tem certeza de que deseja deletar o cliente "@Model.Nome"?</p>

<form asp-action="Delete" method="post" id="formDeletarCliente">
    <input type="hidden" name="id" value="@Model.Id" />
    <button type="submit" class="btn btn-danger">Deletar</button>
    <button type="button" onclick="history.back();" class="btn btn-default">Cancelar</button>

</form>

SwitchSelect/Views/Cliente/EditDadosPessoais.cshtml
@model SwitchSelect.Models.ViewModels.ClienteDadosPessoaisViewModel

@{
    ViewData["Title"] = "EditDadosPessoais";
}

<h1>Editar dados pessoais</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditDadosPessoais" id="formEditarDadosPessoais">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataDeNascimento" class="control-label"></label>
                <input asp-for="DataDeNascimento" class="form-control" />
                <span asp-validation-for="DataDeNascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cpf" class="control-label"></label>
                <input asp-for="Cpf" class="form-control" />
                <span asp-validation-for="Cpf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RG" class="control-label"></label>
                <input asp-for="RG" class="form-control" />
                <span asp-validation-for="RG" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoTelefone" class="control-label"></label>
                <select asp-for="TipoTelefone" class="form-control"></select>
                <span asp-validation-for="TipoTelefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DDD" class="control-label"></label>
                <input asp-for="DDD" class="form-control" />
                <span asp-validation-for="DDD" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroTelefone" class="control-label"></label>
                <input asp-for="NumeroTelefone" class="form-control" />
                <span asp-validation-for="NumeroTelefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" id="editar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SwitchSelect/Views/Cliente/ListaCliente.cshtml
@model IEnumerable<SwitchSelect.Models.Cliente>

@{
    ViewData["Title"] = "ClienteList";
}

<h1>Clientes</h1>
<!--<p>
    <a asp-action="Create">Create New</a>
</p>-->

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataDeNascimento)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.Genero)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cpf)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RG)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataDeNascimento)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cpf)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RG)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Informações</a> |
                <a asp-action="Inativar" asp-route-id="@item.Id">Inativar</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

SwitchSelect/Views/Cliente/PerfilUsuario.cshtml
@{
    ViewData["Title"] = "Área do Usuário";
}

<h2>@ViewData["Title"]</h2>

<div class="container mt-5">
    <div class="row">
        <div class="col-sm-5">
            <div class="list-group-item list-group-item-action">
                <a asp-controller="Pedido" asp-action="Pedido">Pedidos</a>
            </div>
            <div class="list-group-item list-group-item-action">
                <a asp-controller="Cliente" asp-action="PesquisarClientePorCpf">Dados cadastrados</a>
            </div>
            <div class="list-group-item list-group-item-action">
                <a>Cartão</a>
            </div>
        </div>
    </div>
</div>

SwitchSelect/Views/Cliente/PesquisarClientePorCpf.cshtml
@model SwitchSelect.Models.Cliente
@{
    ViewData["Title"] = "Pesquisar cliente";
}
<h2>Entre com seu cpf</h2>

<form asp-controller="Cliente" asp-action="PesquisarPorCpf" method="get">
    <input asp-for="Cpf" placeholder="Digite o CPF" />
    <button type="submit">Pesquisar</button>
</form>