SwitchSelect/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using SwitchSelect.Service;
using SwitchSelect.Models;
using SwitchSelect.Models.ViewModels;

namespace SwitchSelect.Controllers
{
    public class AdminController : Controller
    {
        private readonly AdminService _adminservice;

        public IActionResult TelaAdmin()
        {
            return View();
        }

        public AdminController(AdminService Adminservice)
        {
            _adminservice = Adminservice;

        }

        public IActionResult AdminListaCliente(string pesquisa)
        {
            if (String.IsNullOrEmpty(pesquisa))
            {
                var list = _adminservice.AdminListarClientes();
                return View(list);
            }
            else
            {
                var list = _adminservice.AdminPesquisarCliente(pesquisa);
                return View(list);
            }
        }

        public async Task<IActionResult> AdminInformacaoCliente(int? id)
        {
            if (id == null) { return NotFound(); }

            var cliente = await _adminservice.AdminGetCliente(id.Value);
            if (cliente == null) { return NotFound(); };
            return View(cliente);
        }

    }
}

SwitchSelect/Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;

namespace SwitchSelect.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SwitchSelect/Controllers/JogoController.cs
using Microsoft.AspNetCore.Mvc;
using SwitchSelect.Models;
using SwitchSelect.Models.ViewModels;
using SwitchSelect.Repositorios.Interfaces;

namespace SwitchSelect.Controllers
{
    public class JogoController : Controller
    {
        private readonly IJogoRepositorio _jogoRepositorio;

        public JogoController(IJogoRepositorio jogoRepositorio)
        {
            _jogoRepositorio = jogoRepositorio;
        }

        public IActionResult JogoList(string categoria)
        {
            IEnumerable<Jogo> jogos;
            string categoriaAtual = string.Empty;

            jogos = _jogoRepositorio.Jogos
                    .Where(j => j.Categoria.Nome.Equals(categoria))
                    .OrderBy(j => j.Nome);

            if (jogos.Count() == 0)
            {
                jogos = _jogoRepositorio.Jogos.OrderBy(j => j.Id);
                categoriaAtual = "Todos os Jogos";
            }
            else
            {
                categoriaAtual = categoria;
            }
            var jogoListViewModel = new JogoListViewModel
            {
                Jogos = jogos,
                CategoriaAtual = categoriaAtual
            };
            return View(jogoListViewModel);
        }

        public IActionResult JogosPreferidos()
        {
            var jogosPreferidos = new JogoPreferidoViewModel();
            jogosPreferidos.JogosPreferidos = _jogoRepositorio.JogosPreferidos;

            return View(jogosPreferidos);
        }

        public IActionResult JogoSelecionado()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            var jogo = _jogoRepositorio.Jogos.FirstOrDefault(c => c.Id == id);

            return View(jogo);
        }
    }
}

SwitchSelect/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using SwitchSelect.Data;
using SwitchSelect.Models;
using SwitchSelect.Models.ViewModels;

namespace SwitchSelect.Controllers
{
    public class LoginController : Controller
    {
        private readonly SwitchSelectContext _context;

        public LoginController(SwitchSelectContext context)
        {
            _context = context;
        }

        public IActionResult TelaLogin()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel model)
        {
            if(ModelState.IsValid)
            {
                //verificando cpf de usuário
                var usuario = _context.Clientes.FirstOrDefault(u => u.Cpf == model.Cpf);
                if (usuario != null) 
                {
                    HttpContext.Session.SetString("Cpf", usuario.Cpf);
                    HttpContext.Session.SetString("Nome", usuario.Nome);
                    HttpContext.Session.SetInt32("Id", usuario.Id);
                    return RedirectToAction("AreaCliente","Cliente", new { id = usuario.Id });
                }
                //else
                //{
                //    ModelState.AddModelError(string.Empty, "CPF não encontrado");
                //}
            }
            return View("TelaLogin",model);
        }
    }
}

SwitchSelect/Views/Shared/_JogoResumo.cshtml
@model SwitchSelect.Models.Jogo

<div class="col-md-3 mb-3">
    <div class="text-center">
        <img src="@Url.Content(Model.ImagemUrl)" class="img-fluid" alt="Imagem de @Model.Nome">
    </div>
    <div class="card-body text-center">
        <h5><a asp-controller="Jogo" asp-action="Details" asp-route-id="@Model.Id" 
            style="text-decoration:none">@Model.Nome</a></h5>
        <h6>Preço: @Model.Preco.ToString("c")</h6>
        <div>
            <p class="button">
                <a class="btn btn-primary" id="incluirNoCarrinho" asp-controller="CarrinhoCompra"
                   asp-action="AdicionarItemNoCarrinhoCompra" asp-route-id="@Model.Id">
                    Incluir no carrinho
                </a>
            </p>
        </div>
    </div>
</div>

SwitchSelect/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SwitchSelect</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SwitchSelect.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-g7l36DbRwKhshVoTp54+C5VpH7KNcNU1BfG2vY/2NbB0Slh8jQ1vMvVJzxaZ3TaBWT4r9jMRD7fJl4kFPuCMyw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.1/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"></script>


    <style>
        .nav-input {
            width: 500px; /* Ajuste este valor conforme necessário */
        }
    </style>
</head>
<body>
    <header class="bg-red">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3 py-5 ">
            <div class="container-fluid">
                <a class="navbar-brand header-class-font text-white" asp-area="" asp-controller="Home" asp-action="Index">SwitchSelect</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li>
                            <button id="menu" class="btn text-white" onclick="exibirModalMenu()">
                                <i class="bi bi-list fs-3"></i>
                            </button>
                        </li>

                        <li class="nav-item" style="margin-right: 2.5%">
                            <a class="nav-link header-class-font text-white" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="bi bi-house fs-3"></i>
                            </a>
                        </li>


                        <li class="nav-item" style="margin-right: 5%">
                            @await Component.InvokeAsync("CategoriaMenu")
                        </li>

                        <li class="nav-item" style="margin-right:5%">
                            <div class="input-group nav-input">
                                <input type="text" class="form-control " asp-area="" asp-controller="Home" asp-action="PesquisarJogo" placeholder="O que você quer Jogar?" />
                                <span class="input-group-text">
                                    <img src="~/icones/search.png" />
                                </span>
                            </div>
                        </li>

                        <li class="nav-item" style="margin-right: 5%">
                            <a class="nav-link header-class-font text-white" asp-area="" asp-controller="Login" asp-action="TelaLogin">
                                <i class="bi bi-person fs-3"></i>
                            </a>
                        </li>

                        <li class="nav-item" style="margin-right: 5%">
                            <a asp-controller="Jogo" asp-action="JogosPreferidos" class="nav-link header-class-font text-white ">
                                <i class="bi bi-heart fs-3"></i>
                            </a>
                        </li>
                        <!--Icone carrinho de compra-->
                        <li class="nav-item">
                            <a class="nav-link header-class-font text-white" asp-controller="" asp-action="">
                                <!--<i class="bi bi-cart fs-3"></i>-->
                                <span id="cart-count">@await Component.InvokeAsync("CarrinhoCompraResumo")</span>
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SwitchSelect -
            <a asp-area="" asp-controller="Home" asp-action="Privacy" style="margin-right:2.5%">Privacy</a>
            <a asp-controller="Contato" asp-action="Index" > Contato </a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <!--Modal Menu-->
    <div class="modal" tabindex="-1" role="dialog" id="modalMenu">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Menu</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>

                </div>
                <div class="modal-body">
                    <a asp-controller="Admin" asp-action="TelaAdmin">Área do administrador</a>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>



    <!--Contador de produtos-->
    <script>

        function exibirModalMenu() {
            $('#modalMenu').modal('show');
        }

    </script>

</body>
</html>