SwitchSelect/Models/Jogo/Jogo.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SwitchSelect.Models;


[Table("Jogos")]
public class Jogo
{
    [Key]
    public int Id { get; set; }

    [Required(ErrorMessage = "Informe o nome do jogo")]
    [StringLength(100, ErrorMessage = "O tamanho máximo é de 100 caracteres")]
    [Display(Name = "Nome")]
    public string Nome { get; set; }

    [Required(ErrorMessage = "Informe o Preço do jogo")]
    [Display(Name = "Preço")]
    [Column(TypeName = "decimal(10,2)")]
    [Range(1, 999.99, ErrorMessage = "O valor deve estar ente 1 e 999,99")]
    public decimal Preco { get; set; }

    [Required(ErrorMessage = "Informe o caminho da imagem")]
    [StringLength(100, ErrorMessage = "O tamanho máximo é de 100 cacteres")]
    [Display(Name = "Caminho da imagem")]
    public string ImagemUrl { get; set; }

    [Display(Name = "Preferido")]
    public bool? IsJogoPreferido { get; set; }

    [Display(Name = "Estoque")]
    public bool? EmEstoque { get; set; }
   
    public int CategoriaID { get; set; }
    public virtual Categoria Categoria { get; set; }


}

SwitchSelect/Models/ViewModels/JogoListViewModel.cs
namespace SwitchSelect.Models.ViewModels;

public class JogoListViewModel
{
    public IEnumerable<Jogo> Jogos { get; set; }
    public string CategoriaAtual { get; set; }

}

SwitchSelect/Controllers/CarrinhoCompraController.cs
using Microsoft.AspNetCore.Mvc;
using SwitchSelect.Models.Carrinho;
using SwitchSelect.Models.ViewModels;
using SwitchSelect.Repositorios.Interfaces;

namespace SwitchSelect.Controllers
{
    public class CarrinhoCompraController : Controller
    {
        private readonly IJogoRepositorio _jogoRepositorio;
        private readonly CarrinhoCompra _carrinhoCompra;

        public CarrinhoCompraController(IJogoRepositorio jogoRepositorio, CarrinhoCompra carrinhoCompra)
        {
            _jogoRepositorio = jogoRepositorio;
            _carrinhoCompra = carrinhoCompra;
        }

        public IActionResult Index()
        {
            var itens = _carrinhoCompra.GetCarrinhosCompraItens();
            _carrinhoCompra.CarrinhosCompraItens = itens;

            var carrinhoComprasVM = new CarrinhoCompraViewModel
            {
                CarrinhoCompra = _carrinhoCompra,
                CarrinhoCompraTotal = _carrinhoCompra.GetCarrinhoCompraTotal(),
            };
            return View(carrinhoComprasVM);
        }

        public IActionResult AdicionarItemNoCarrinhoCompra(int id)
        {
            var jogoSelecionado = _jogoRepositorio.Jogos.FirstOrDefault(j => j.Id == id);
            if(jogoSelecionado != null)
            {
                _carrinhoCompra.AdicionarAoCarrinho(jogoSelecionado);
            }
            return RedirectToAction("Index");
        }

        public IActionResult RemoverItemDoCarrinhoCompra(int id)
        {
            var jogoSelecionado = _jogoRepositorio.Jogos.FirstOrDefault(j => j.Id == id);
            if(jogoSelecionado != null)
            {
                _carrinhoCompra.RemoverDoCarrinho(jogoSelecionado);
            }
            return RedirectToAction("Index");
        }

        
    }
}

SwitchSelect/Controllers/CarrinhoDeCompraController.cs
using Microsoft.AspNetCore.Mvc;

namespace SwitchSelect.Controllers
{
    public class CarrinhoDeCompraController : Controller
    {
       public IActionResult Carrinho()
        {
            return View();
        }
       
    }
}

SwitchSelect/Controllers/CheckoutController.cs
using Microsoft.AspNetCore.Mvc;

namespace SwitchSelect.Controllers
{
    public class CheckoutController : Controller
    {
        public IActionResult Checkout()
        {
            return View();
        }
    }
}

SwitchSelect/Controllers/JogoController.cs
using Microsoft.AspNetCore.Mvc;
using SwitchSelect.Models;
using SwitchSelect.Models.ViewModels;
using SwitchSelect.Repositorios.Interfaces;

namespace SwitchSelect.Controllers
{
    public class JogoController : Controller
    {
        private readonly IJogoRepositorio _jogoRepositorio;

        public JogoController(IJogoRepositorio jogoRepositorio)
        {
            _jogoRepositorio = jogoRepositorio;
        }

        public IActionResult JogoList(string categoria)
        {
            IEnumerable<Jogo> jogos;
            string categoriaAtual = string.Empty;

            jogos = _jogoRepositorio.Jogos
                    .Where(j => j.Categoria.Nome.Equals(categoria))
                    .OrderBy(j => j.Nome);

            if (jogos.Count() == 0)
            {
                jogos = _jogoRepositorio.Jogos.OrderBy(j => j.Id);
                categoriaAtual = "Todos os Jogos";
            }
            else
            {
                categoriaAtual = categoria;
            }
            var jogoListViewModel = new JogoListViewModel
            {
                Jogos = jogos,
                CategoriaAtual = categoriaAtual
            };
            return View(jogoListViewModel);
        }

        public IActionResult JogosPreferidos()
        {
            var jogosPreferidos = new JogoPreferidoViewModel();
            jogosPreferidos.JogosPreferidos = _jogoRepositorio.JogosPreferidos;

            return View(jogosPreferidos);
        }

        public IActionResult JogoSelecionado()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            var jogo = _jogoRepositorio.Jogos.FirstOrDefault(c => c.Id == id);

            return View(jogo);
        }
    }
}

SwitchSelect/Views/Jogo/Details.cshtml
@model SwitchSelect.Models.Jogo

<style>
    .nav-input {
        width: 500px;
        /* Ajuste este valor conforme necessário */
    }
</style>

<!--Pagina Index do jogo (escolhido)-->
<div class="container">
    <div class="row">
        <div class="col-12 col-md-5">

            <img src="@Url.Content(Model.ImagemUrl)" class="img-fluid" alt="" />
        </div>
        <div class="col-12 col-md-7 ">
            <h1>
                @Model.Nome - Nintendo Switch
            </h1>
            <br>
            <p class="fs-5">
                SwitchSelect, a melhor loja de Nintendo do Brasil, aqui somos Nintendista para você se sentir
                em casa, a melhor loja de Nintendo do Brasil, aqui somos Nintendista para você se sentir em casa
            </p>
            
            <h5 class="card-title">@Model.Nome</h5>
            <p class="card-text">
                Categoria: @Model.Categoria.Nome.
                <br /> @Model.Categoria.Descricao
            </p>
            <p class="fs-3 text-danger">R$@Model.Preco</p>
            <p class="btn btn-group align-content-lg-end">
                <a asp-controller="Jogo" asp-action="JogoList" class="btn btn-outline-info">
                    Ver todos os jogos
                </a>

                <a asp-controller="CarrinhoCompra" asp-action="AdicionarItemNoCarrinhoCompra"
                   asp-route-id="@Model.Id" class="btn btn-primary">Adicionar @Model.Nome ao carrinho</a>
            </p>

        </div>
    </div>
</div>

SwitchSelect/Views/Jogo/JogoList.cshtml
@model SwitchSelect.Models.ViewModels.JogoListViewModel;

<h2>Os melhores jogos para Nitendo Switch</h2>


<div class="container">
    <div class="row text-center">
        @foreach (var jogo in Model.Jogos)
        {
            <partial name="_jogoResumo" for="@jogo" />
        }
    </div>
</div>

SwitchSelect/Views/Jogo/JogoSelecionado.cshtml
@{
    ViewData["Title"] = "Another Code";
}
<style>
    .nav-input {
        width: 500px;
        /* Ajuste este valor conforme necessário */
    }
</style>

<!--Pagina Index do jogo (escolhido)-->
<div class="container">
    <div class="row">
        <div class="col-12 col-md-5">

            <img src="~/imagens/acr-png-2-484x484.png" class="img-fluid" />
            <p class="fs-4 mt-2 text-center">Another Code Recollection</p>
            <p class="text-center">R$249 à vista ou 4X de R$69,44</p>

        </div>
        <div class="col-12 col-md-7 ">
            <h1>
                Another Code: Recollection - Nintendo Switch
            </h1>
            <br>
            <p class="fs-5">
                SwitchSelect, a melhor loja de Nintendo do Brasil, aqui somos Nintendista para você se sentir
                em casa, a melhor loja de Nintendo do Brasil, aqui somos Nintendista para você se sentir em casa
            </p>
            <br>
            <p class="fs-3 text-danger">R$ 249,00 à vista </p>
            <p>
                OU <span class="text-danger">4X</span> DE <span class="text-danger">R$69,44</span> NO CARTÃO SEM
                JUROS OU EM ATÉ 12X COM JUROS
            </p>

            <div class="d-flex justify-content-start align-items-center">
                <p>QTD</p>
                <input type="number" class="form-control" style="width: 100px; margin-right: 10px;" value="1"
                       min="1">
              
                <button id="adicionarCarrinho" class="btn btn-secondary me-2" type="button" data-bs-toggle="modal" data-bs-target="#carrinhoModal">
                    Adicionar ao Carrinho
                </button>


                <a asp-controller="Checkout" asp-action="Checkout" class="btn btn-primary" type="button">Comprar Agora</a>
            </div>

        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="carrinhoModal" tabindex="-1" aria-labelledby="carrinhoModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="carrinhoModalLabel">Carrinho de Compras</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p class="fs-3">Tudo Certo!</p>
                <p>Você adicionou Another Code Revollution ao carrinho de compra.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Continuar Navegando</button>
                <a asp-area="" asp-controller="CarrinhoDeCompra" asp-action="Carrinho" class="btn btn-primary">Ver Carrinho</a>
            </div>
        </div>
    </div>
</div>

SwitchSelect/Views/Jogo/JogosPreferidos.cshtml
@model SwitchSelect.Models.ViewModels.JogoPreferidoViewModel;

<h2>Jogos recomendados</h2>

<div class="row">
    @foreach (var jogo in Model.JogosPreferidos)
    {
        <partial name="_JogoResumo" for="@jogo" />
    }

</div>